# Generated by Django 4.1 on 2022-09-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='slug',
        ),
    ]
